GET http://localhost:3838/api/products

###
GET http://localhost:3838/api/products/2b1527e9-e82a-4a63-bd2b-2e0096465d20

###
PUT http://localhost:3838/api/products/2b1527e9-e82a-4a63-bd2b-2e0096465d20
Content-Type: application/json

{
  "name": "Caneta atualizada",
}

###
DELETE http://localhost:3838/api/products/2b1527e9-e82a-4a63-bd2b-2e0096465d20
